version: 0.2
env:
  secrets-manager:
    SONAR_TOKEN: dev/codebuild/sonarqube/credentials:tokenForSonar
phases:
  install:
    runtime-versions:
      java: latest
    commands:
      - echo "Installing jq for JSON processing"
      - yum install -y jq
  build:
    commands:
      - echo "Running SonarQube Analysis"
      - mvn clean verify sonar:sonar -Dsonar.projectKey=devsecops01 -Dsonar.host.url=http://3.139.145.182:9000 -Dsonar.login=$SONAR_TOKEN
